//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.09 at 04:50:30 AM WET 
//


package ma.jberrich.swingmap.server.jaxb.timezone;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ma.supmti.jaxb.timezone package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CountryName_QNAME = new QName("", "countryName");
    private final static QName _Time_QNAME = new QName("", "time");
    private final static QName _Sunset_QNAME = new QName("", "sunset");
    private final static QName _RawOffset_QNAME = new QName("", "rawOffset");
    private final static QName _DstOffset_QNAME = new QName("", "dstOffset");
    private final static QName _CountryCode_QNAME = new QName("", "countryCode");
    private final static QName _GmtOffset_QNAME = new QName("", "gmtOffset");
    private final static QName _Lng_QNAME = new QName("", "lng");
    private final static QName _Sunrise_QNAME = new QName("", "sunrise");
    private final static QName _TimezoneId_QNAME = new QName("", "timezoneId");
    private final static QName _Lat_QNAME = new QName("", "lat");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ma.supmti.jaxb.timezone
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Timezone }
     * 
     */
    public Timezone createTimezone() {
        return new Timezone();
    }

    /**
     * Create an instance of {@link Geonames }
     * 
     */
    public Geonames createGeonames() {
        return new Geonames();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "countryName")
    public JAXBElement<String> createCountryName(String value) {
        return new JAXBElement<String>(_CountryName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time")
    public JAXBElement<String> createTime(String value) {
        return new JAXBElement<String>(_Time_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sunset")
    public JAXBElement<String> createSunset(String value) {
        return new JAXBElement<String>(_Sunset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rawOffset")
    public JAXBElement<BigDecimal> createRawOffset(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RawOffset_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dstOffset")
    public JAXBElement<BigDecimal> createDstOffset(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DstOffset_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "countryCode")
    public JAXBElement<String> createCountryCode(String value) {
        return new JAXBElement<String>(_CountryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gmtOffset")
    public JAXBElement<BigDecimal> createGmtOffset(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GmtOffset_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lng")
    public JAXBElement<Double> createLng(Double value) {
        return new JAXBElement<Double>(_Lng_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sunrise")
    public JAXBElement<String> createSunrise(String value) {
        return new JAXBElement<String>(_Sunrise_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "timezoneId")
    public JAXBElement<String> createTimezoneId(String value) {
        return new JAXBElement<String>(_TimezoneId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lat")
    public JAXBElement<Double> createLat(Double value) {
        return new JAXBElement<Double>(_Lat_QNAME, Double.class, null, value);
    }

}
