//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.09 at 04:50:30 AM WET 
//


package ma.ensao.swingmap.server.jaxb.timezone;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}countryCode"/>
 *         &lt;element ref="{}countryName"/>
 *         &lt;element ref="{}lat"/>
 *         &lt;element ref="{}lng"/>
 *         &lt;element ref="{}timezoneId"/>
 *         &lt;element ref="{}dstOffset"/>
 *         &lt;element ref="{}gmtOffset"/>
 *         &lt;element ref="{}rawOffset"/>
 *         &lt;element ref="{}time"/>
 *         &lt;element ref="{}sunrise"/>
 *         &lt;element ref="{}sunset"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tzversion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "countryCode",
    "countryName",
    "lat",
    "lng",
    "timezoneId",
    "dstOffset",
    "gmtOffset",
    "rawOffset",
    "time",
    "sunrise",
    "sunset"
})
@XmlRootElement(name = "timezone")
public class Timezone {

    @XmlElement(required = true)
    protected String countryCode;
    @XmlElement(required = true)
    protected String countryName;
    protected double lat;
    protected double lng;
    @XmlElement(required = true)
    protected String timezoneId;
    @XmlElement(required = true)
    protected BigDecimal dstOffset;
    @XmlElement(required = true)
    protected BigDecimal gmtOffset;
    @XmlElement(required = true)
    protected BigDecimal rawOffset;
    @XmlElement(required = true)
    protected String time;
    @XmlElement(required = true)
    protected String sunrise;
    @XmlElement(required = true)
    protected String sunset;
    @XmlAttribute(name = "tzversion", required = true)
    protected String tzversion;

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the countryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the value of the countryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryName(String value) {
        this.countryName = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     */
    public double getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     */
    public void setLat(double value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lng property.
     * 
     */
    public double getLng() {
        return lng;
    }

    /**
     * Sets the value of the lng property.
     * 
     */
    public void setLng(double value) {
        this.lng = value;
    }

    /**
     * Gets the value of the timezoneId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezoneId() {
        return timezoneId;
    }

    /**
     * Sets the value of the timezoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezoneId(String value) {
        this.timezoneId = value;
    }

    /**
     * Gets the value of the dstOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDstOffset() {
        return dstOffset;
    }

    /**
     * Sets the value of the dstOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDstOffset(BigDecimal value) {
        this.dstOffset = value;
    }

    /**
     * Gets the value of the gmtOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGmtOffset() {
        return gmtOffset;
    }

    /**
     * Sets the value of the gmtOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGmtOffset(BigDecimal value) {
        this.gmtOffset = value;
    }

    /**
     * Gets the value of the rawOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRawOffset() {
        return rawOffset;
    }

    /**
     * Sets the value of the rawOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRawOffset(BigDecimal value) {
        this.rawOffset = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the sunrise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSunrise() {
        return sunrise;
    }

    /**
     * Sets the value of the sunrise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSunrise(String value) {
        this.sunrise = value;
    }

    /**
     * Gets the value of the sunset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSunset() {
        return sunset;
    }

    /**
     * Sets the value of the sunset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSunset(String value) {
        this.sunset = value;
    }

    /**
     * Gets the value of the tzversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTzversion() {
        return tzversion;
    }

    /**
     * Sets the value of the tzversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTzversion(String value) {
        this.tzversion = value;
    }

}
